package common.dto;

public enum TipOperatie {
    INREGISTRARE_PACIENT,
    INREGISTRARE_DOCTOR,
    LOGIN,
    VIZUALIZARE_PROGRAMARI_PACIENT,
    VIZUALIZARE_PROGRAMARI_DOCTOR,
    VIZUALIZARE_DOCTORI,
    CREARE_PROGRAMARE
}
